<?php
$model = $this->getPayment();
$checkout_type = $model->getConfigValue('checkout_mode');
$mode = $model->getConfigValue('operation_mode');
if ($checkout_type == 'paymentjs') {
    if ($mode == 'test') {
?>
        <script data-main="payment-js" src="https://asxgw.paymentsandbox.cloud/js/integrated/payment.1.3.min.js"></script>
<?php
    } else {
?>
        <script data-main="payment-js" src="https://asxgw.com/js/integrated/payment.1.3.min.js"></script>
<?php
    }
}


